### ISSUE TITLE
SD Gundam Gaiden - Knight Gundam Monogatari 2 Does not load

### ISSUE THREAD

**Issue by BlackPaladin2022** [saulfabregwiivc/FCEUXTX#4]
This is a Mapper 16 ROM.  While the emulator can run some, this one does not run on FCEUX TX.  Loading the game will result in a grey screen displayed, nothing else.

I've tested it on my Nintendo Wii, which has 4.3U firmware and is jailbroken with letterbomb.

1.  Load FCEUX TX
2.  Select ROM to load on FCEUX TX
3.  *optional*  Reset game, but the result is the same

I've included the hashes for the game in case it's needed.

Database match: SD Gundam Gaiden - Knight Gundam Monogatari 2 - Hikari no Knight (Japan)
Database: No-Intro: Nintendo Entertainment System (v. 20210216-231042)
File SHA-1: 2AD24D6EF5A329254991FBF5E89A2C13E14799C3
File CRC32: C1319DD
ROM SHA-1: D08C0D7D333D338FD5CA1994CEA81C5A9EED65E5
ROM CRC32: B049A8C4

**Comment by saulfabregwiivc** [comment]
I will tell the original author (Tanooki16) about this issue.
I only created this repo for mirror FCEUX TX's code.

**Comment by saulfabregwiivc** [comment]
Tanooki16:
It's a rom problem, maybe your ROM is corrupted? Because this game is actually playable on FCEUX TX.
I will post in a few minutes an evidence.

**Comment by saulfabregwiivc** [comment]
Evidence that this game is working:
https://gbatemp.net/threads/fceugx-1up.558023/post-10108977

Closing this one since i bet you're using a broken or corrupted ROM.
