### ISSUE TITLE
FDS saving issue 

### ISSUE THREAD

**Issue by pokemonfan6498** [saulfabregwiivc/FCEUXTX#7]
i was playing esper dream but when i decided to continue where i left off all my save data was fone as if saving did nothing i checked the saves folder and there were no save files for fds games same issue appears in every single game

**Comment by saulfabregwiivc** [comment]
FCEUX TX and its previous forks (FCE Ultra GX, FCEURX) doesn't support writing FDS savedata to disk or a savefile.

Better use savestates, or another NES emu for Wii such Nestopia on RetroArch.

**Comment by pokemonfan6498** [comment]
i hope later versions of this emulator will add support for saving in fds
games because retroarch is unstable
